Repository relativityone/azure-storage-net-data-movement, pull requests merged in 2021-12, with the labels that each got.

#8 DM-1 fork preparations for Relativity
  .buildtools/BuildHelpers.psm1
  .gitignore
  DMLibTest_NetStandard.sln
  DataMovement.sln
  DataMovement_k.sln
  build.ps1
  lib/DataMovement.csproj
  netcore/DMLibTest/DMLibTest.csproj
  netcore/DMLibTest/TestData.xml
  netcore/DMLibTestCodeGen_NetCore/DMLibTestCodeGen_NetCore.csproj
  netcore/Microsoft.Azure.Storage.DataMovement/Microsoft.Azure.Storage.DataMovement.csproj
  psakefile.ps1
  test/DMLibTest/Cases/AccessConditionTest.cs
  test/DMLibTest/Cases/FollowSymlinkTest.cs
  test/DMLibTest/Cases/LongFilePathTest.cs
  test/DMLibTest/DMLibTest.csproj
  test/DMLibTest/TestData.xml
  test/DMLibTest/app.config
  test/DMLibTest/packages.config
  test/DMLibTestCodeGen/App.config
  test/DMLibTestCodeGen/DMLibTestCodeGen.csproj
  test/DMLibTestCodeGen/MultiDirectionTestClass.cs
  test/DMLibTestCodeGen/Program.cs
  test/DMLibTestCodeGen/SourceCodeGenerator.cs
  test/DMLibTestCodeGen/packages.config
  test/DMLibTest_NetStandard/DMLibTest_NetStandard.csproj
  test/DMLibTest_NetStandard/app.config
  test/DMLibTest_NetStandard/packages.config
  test/DMTestLib/DMLibTestMetholdAttribute.cs
  test/DMTestLib/DMLibTransferDirection.cs
  test/DMTestLib/DMTestLib.csproj
  test/DMTestLib/MultiDirectionTestClassAttribute.cs
  test/DMTestLib/MultiDirectionTestMethod.cs
  test/DMTestLib/MultiDirectionTestMethodAttribute.cs
  test/DMTestLib/TestMethodDirection.cs
  test/DMTestLib/packages.config
  test/MsTestLib/MsTestLib.csproj
  test/MsTestLib/TestConfig.cs
  test/MsTestLib/packages.config
Labels: size/XL

#9 [DM-1] readme update
  README.md
Labels: size/M

#11 Dm 1 update readme file
  README.md
Labels: size/XS

#10 Rel 620891 narrow the test set to reduce execution time
  test/DMLibTest/Cases/BVT.cs
  test/DMLibTest/Cases/FollowSymlinkTest.cs
  test/DMLibTest/Cases/LongFilePathTest.cs
  test/DMLibTest/Cases/OverwriteTest.cs
  test/DMLibTest/Cases/ResumeTest.cs
  test/DMLibTest/Cases/SASTokenVersionTest.cs
  test/DMLibTest/Cases/SMBPropertiesTest.cs
  test/DMLibTest/Cases/SetAttributesTest.cs
  test/DMLibTestCodeGen/DMLibDataTypeExtentions.cs
  test/DMLibTestCodeGen/DMLibTestCodeGen.csproj
  test/DMLibTestCodeGen/DMLibTransferDirectionExtensions.cs
  test/DMLibTestCodeGen/SourceCodeGenerator.cs
  test/DMTestLib/DMLibTestMethodSet.cs
Labels: size/L

#12 REL-620891 DMLibTransferDirectionExtensions.IsCopyTest() fixed
  test/DMLibTestCodeGen/DMLibTransferDirectionExtensions.cs
Labels: size/XS

#14 Rel 623163 fix linux tests
  netcore/DMLibTest/DMLibTest.csproj
  test/DMLibTest/Cases/SearchPatternTest.cs
  test/DMLibTest/Cases/SetAttributesTest.cs
Labels: size/S

#15 REL-620315
  DataMovement.sln
  LICENSE
  netcore/DMLibTest/DMLibTest.csproj
  netcore/Microsoft.Azure.Storage.DataMovement/Microsoft.Azure.Storage.DataMovement.csproj
  psakefile.ps1
  tools/AssemblyInfo/SharedAssemblyInfo.cs
  tools/nupkg/Microsoft.Azure.Storage.DataMovement.nuspec
  tools/nupkg/buildDebugNupkg.cmd
  tools/nupkg/buildNupkg.cmd
  tools/scripts/InjectBuildNumber.ps1
  version.txt
Labels: size/L

#7 Rel 618417
  lib/AssemblyInfo.cs
  lib/DataMovement.csproj
  lib/Exceptions/TransferErrorCode.cs
  lib/Exceptions/TransferInvalidPathException.cs
  lib/Resources.Designer.cs
  lib/Resources.resx
  lib/TransferCallbacks.cs
  lib/TransferContext.cs
  lib/TransferControllers/SyncTransferController.cs
  lib/TransferJobs/SingleObjectTransfer.cs
  netcore/DMLibTest/TestClassFixtures.cs
  netcore/Microsoft.Azure.Storage.DataMovement/Microsoft.Azure.Storage.DataMovement.csproj
  test/DMLibTest/Cases/ValidateDestinationPathTest.cs
  test/DMLibTest/DMLibTest.csproj
  test/DMLibTest/Framework/DMLibInputHelper.cs
  tools/AssemblyInfo/SharedAssemblyInfo.cs
  version.txt
Labels: size/L

#17 Fixed assembly version
  netcore/Microsoft.Azure.Storage.DataMovement/Microsoft.Azure.Storage.DataMovement.csproj
  tools/AssemblyInfo/SharedAssemblyInfo.cs
  tools/scripts/InjectBuildNumber.ps1
  version.txt
Labels: bug, size/S
